// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
import type { SourceModule } from './src/modules/Source';

export type { OASISResponse, OASISSession };

export interface Web10ClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class Web10Client {
  constructor(options?: Web10ClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
  readonly source: SourceModule;
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
}

export default Web10Client;
