'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { SourceModule } = require('./Source');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.source = client.source || new SourceModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
