// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SourceModule {
  constructor(http: unknown);

  /** GET v1/source/ */
  getSource(args?: Record<string, any>): Promise<OASISResponse>;
}
