'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/source (source: WEB10 Source WebAPI SourceController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SourceModule {
  constructor(http) {
    this._http = http;

    // get v1/source/
    this.getSource = makeOperation(http, "v1/source", "GET", "");
  }
}

module.exports = { SourceModule };
